module.exports = {
	API_CHANGE: 'API_CHANGE',
	ROUTE_CHANGE: 'ROUTE_CHANGE',
	RESPONSE_CHANGE: 'RESPONSE_CHANGE',
	USER_CHANGE: 'USER_CHANGE',
	METHOD_CHANGE: 'METHOD_CHANGE',
	SAFE_REQUEST_CHANGE: 'SAFE_REQUEST_CHANGE',
	SUBMIT_REQUEST: 'SUBMIT_REQUEST',
};
